### ISSUE TITLE
Typo in theory in README.md?

### ISSUE THREAD

**Issue by MYIP003** [milankl/LinLogQuantization.jl#8]
For the linear quantization theory, should be `Δ = (2^n-1)/(Amax-Amin)`instead of `Δ = 2^(n-1)/(Amax-Amin)`?
And for the logarithmic quantization theory as well, should that be `Δ = (2^n-2)/(logmax-logmin)` instead of `Δ = 2^(n-2)/(logmax-logmin)`?

**Comment by milankl** [comment]
Yes, typo, as you can see from the code
https://github.com/milankl/LinLogQuantization.jl/blob/96212f42a77894d6734838a00d82071f5883c15b/src/linquantarrays.jl#L23
https://github.com/milankl/LinLogQuantization.jl/blob/96212f42a77894d6734838a00d82071f5883c15b/src/logquantarrays.jl#L42

Thanks for pointing it out!

**Comment by milankl** [comment]
Leaving this issue open for now in case you find more typos ;)
